import Foundation
import CoreGraphics

struct TEIPage {
    var imageURL: URL
    var imageSize: CGSize
    var lines: [OCRLine]
}

struct TEIMeta {
    var title: String = "Untitled"
    var responsibleName: String = ""
    var date: String = isoToday()
    var language: String = "en"

    static func isoToday() -> String {
        let f = DateFormatter()
        f.dateFormat = "yyyy-MM-dd"
        f.locale = Locale(identifier: "en_US_POSIX")
        return f.string(from: Date())
    }
}

enum TEIBuilder {
    static func build(pages: [TEIPage], meta: TEIMeta) -> String {
        var out = String()
        out.reserveCapacity(8 * 1024)

        out += #"<?xml version="1.0" encoding="UTF-8"?>"# + "\n"
        out += #"<TEI xmlns="http://www.tei-c.org/ns/1.0" xml:lang="\#(esc(meta.language))">"# + "\n"
        out += teiHeader(meta: meta)
        out += facsimile(pages: pages)
        out += textBody(pages: pages)
        out += "</TEI>\n"
        return out
    }

    // MARK: - teiHeader

    private static func teiHeader(meta: TEIMeta) -> String {
        var s = "  <teiHeader>\n"
        s += "    <fileDesc>\n"
        s += "      <titleStmt>\n"
        s += "        <title>\(esc(meta.title))</title>\n"
        if !meta.responsibleName.isEmpty {
            s += "        <respStmt>\n"
            s += "          <resp>TEI encoding</resp>\n"
            s += "          <name>\(esc(meta.responsibleName))</name>\n"
            s += "        </respStmt>\n"
        }
        s += "      </titleStmt>\n"
        s += "      <publicationStmt>\n"
        s += "        <publisher>—</publisher>\n"
        s += "        <date when=\"\(esc(meta.date))\"/>\n"
        s += "      </publicationStmt>\n"
        s += "      <sourceDesc>\n"
        s += "        <p>Generated by TEIScanner from OCR of scanned page images.</p>\n"
        s += "      </sourceDesc>\n"
        s += "    </fileDesc>\n"
        s += "  </teiHeader>\n"
        return s
    }

    // MARK: - facsimile

    private static func facsimile(pages: [TEIPage]) -> String {
        var s = "  <facsimile>\n"
        for (i, page) in pages.enumerated() {
            let surfaceID = surfaceID(index: i)
            let w = Int(page.imageSize.width.rounded())
            let h = Int(page.imageSize.height.rounded())
            s += "    <surface xml:id=\"\(surfaceID)\" ulx=\"0\" uly=\"0\" lrx=\"\(w)\" lry=\"\(h)\">\n"
            s += "      <graphic url=\"\(esc(page.imageURL.lastPathComponent))\" width=\"\(w)px\" height=\"\(h)px\"/>\n"
            for (j, line) in page.lines.enumerated() {
                let zoneID = zoneID(pageIndex: i, lineIndex: j)
                let ulx = Int(line.box.origin.x.rounded())
                let uly = Int(line.box.origin.y.rounded())
                let lrx = Int((line.box.origin.x + line.box.size.width).rounded())
                let lry = Int((line.box.origin.y + line.box.size.height).rounded())
                s += "      <zone xml:id=\"\(zoneID)\" ulx=\"\(ulx)\" uly=\"\(uly)\" lrx=\"\(lrx)\" lry=\"\(lry)\"/>\n"
            }
            s += "    </surface>\n"
        }
        s += "  </facsimile>\n"
        return s
    }

    // MARK: - text/body

    /// Emits the transcription as `<pb>` / `<lb>` milestones inside a single
    /// `<p>`. Each line is an `<lb>` whose `corresp` points at its `<zone>`,
    /// with the OCR text following the milestone. This is the structure the
    /// TEI/IIIF editor parses (see its `public/samples/sample-tei.xml`).
    private static func textBody(pages: [TEIPage]) -> String {
        var s = "  <text>\n    <body>\n      <p>\n"
        for (i, page) in pages.enumerated() {
            let surfaceID = surfaceID(index: i)
            s += "        <pb n=\"\(i + 1)\" facs=\"#\(surfaceID)\"/>\n"
            for (j, line) in page.lines.enumerated() {
                let zoneID = zoneID(pageIndex: i, lineIndex: j)
                s += "        <lb corresp=\"#\(zoneID)\" n=\"\(j + 1)\" type=\"line\"/>\(esc(line.text))\n"
            }
        }
        s += "      </p>\n    </body>\n  </text>\n"
        return s
    }

    // MARK: - helpers

    private static func surfaceID(index: Int) -> String { "f\(index + 1)" }
    private static func zoneID(pageIndex: Int, lineIndex: Int) -> String {
        "f\(pageIndex + 1)_l\(lineIndex + 1)"
    }

    static func esc(_ s: String) -> String {
        var r = String()
        r.reserveCapacity(s.count)
        for c in s {
            switch c {
            case "&": r += "&amp;"
            case "<": r += "&lt;"
            case ">": r += "&gt;"
            case "\"": r += "&quot;"
            case "'": r += "&apos;"
            default: r.append(c)
            }
        }
        return r
    }
}
