#!/usr/bin/env python3
"""
Crop a Gemini-generated 2048x2048 icon (with bottom-right watermark),
resize to 1024 master, and write all macOS AppIcon.appiconset PNGs
plus Contents.json.

Usage:
    python3 scripts/build_icon.py /path/to/source.png
"""
import argparse
import json
import os
import sys

from PIL import Image

ICONSET = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "Resources", "Assets.xcassets", "AppIcon.appiconset",
)

# (size, scale) — macOS App Icon set
MACOS_VARIANTS = [
    (16, 1), (16, 2),
    (32, 1), (32, 2),
    (128, 1), (128, 2),
    (256, 1), (256, 2),
    (512, 1), (512, 2),
]


def crop_and_resize(source_path: str, master_size: int = 1024, margin: int = 130) -> Image.Image:
    img = Image.open(source_path)
    w, h = img.size
    if w != h:
        raise SystemExit(f"expected square image, got {w}x{h}")
    cropped = img.crop((margin, margin, w - margin, h - margin))
    master = cropped.resize((master_size, master_size), Image.LANCZOS).convert("RGB")
    return master


def write_iconset(master: Image.Image) -> None:
    os.makedirs(ICONSET, exist_ok=True)
    images = []
    written = set()
    for size, scale in MACOS_VARIANTS:
        px = size * scale
        filename = f"icon_{size}x{size}@{scale}x.png"
        if px not in written:
            target = master.resize((px, px), Image.LANCZOS)
            target.save(os.path.join(ICONSET, filename), "PNG", optimize=True)
            written.add(px)
        else:
            # Symlink not needed; just ensure file exists. Actually each
            # (size, scale) is unique by filename, so always write.
            target = master.resize((px, px), Image.LANCZOS)
            target.save(os.path.join(ICONSET, filename), "PNG", optimize=True)
        images.append({
            "size": f"{size}x{size}",
            "idiom": "mac",
            "filename": filename,
            "scale": f"{scale}x",
        })
    contents = {
        "images": images,
        "info": {"version": 1, "author": "xcode"},
    }
    with open(os.path.join(ICONSET, "Contents.json"), "w") as f:
        json.dump(contents, f, indent=2)


def write_top_level_assets() -> None:
    top = os.path.dirname(ICONSET)
    with open(os.path.join(top, "Contents.json"), "w") as f:
        json.dump({"info": {"version": 1, "author": "xcode"}}, f, indent=2)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("source", help="2048x2048 PNG generated by Gemini etc.")
    ap.add_argument("--margin", type=int, default=130, help="px to crop from each side (default 130)")
    args = ap.parse_args()

    master = crop_and_resize(args.source, master_size=1024, margin=args.margin)
    write_iconset(master)
    write_top_level_assets()
    print(f"Wrote AppIcon.appiconset to {ICONSET}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
